### ISSUE TITLE
Open Stash With password option is not working !!

### ISSUE THREAD

**Issue by subhampro** [OmiJod/moon-warehouse#1]
If you need any video clip of this bug ask ! I will upload

**Comment by Catblury** [comment]
> If you need any video clip of this bug ask ! I will upload

u are also a developer u should know how to fix it ?

**Comment by subhampro** [comment]
> > If you need any video clip of this bug ask ! I will upload
> 
> u are also a developer u should know how to fix it ?

Hey brother! I had not created the script. So I need to read all of the code, then I can fix this. But the owner of the script knows where to fix it, and it's millisecond work for him. That's why I created an issue. And thanks for remembering me that I am a developer too soon. I am going to rewrite the script with many more feathers for big servers like mine. [India's No. 1 BL Server Elapsed Roleplay] + As I can see, you are a Bengali. I have some words for you in Bengali. Mr. Kaushik Biswas:: Bengalis ei jonnoi bodnam loker pichone poke na kore nije kichu kore dekhao jibone!!! closed issue te reply na kore nijer kichu banao..
